remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Home: ''
  - Welcome to PEARC21 Tapis User Meeting: welcome/intro
  - Tapis V3 introduction and V2 changes: block1/TapisIntro
  - Tapis V3 Demo: block1/demo
  - User Stories - A2CPS: block1/a2cps
  - User Stories - UH and Associate Sites: block1/uh_associate_site
  - Tapis Roadmap: block1/roadmap
  - Contributing to Tapis: block1/coc


theme: jekyll-theme-hacker